apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: sensor-filtering
spec:
  template:
    serviceAccountName: operate-workflow-sa
  dependencies:
    - name: dep1
      eventSourceName: sensor-filter-es
      eventName: example
      filters:
        data:
          - path: body.value
            type: number
            comparator: ">"
            value:
              - "50.0"
  triggers:
    - template:
        name: wf-trigger
        k8s:
          operation: create
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                generateName: hello-world-
              spec:
                entrypoint: whalesay
                arguments:
                  parameters:
                    - name: message
                      value: hello world
                templates:
                  - name: whalesay
                    inputs:
                      parameters:
                        - name: message
                    container:
                      image: docker/whalesay
                      command: [cowsay]
                      args: ["{{inputs.parameters.message}}"]
