apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: hook-demo-
spec:
  entrypoint: main
  hooks:
    exit:
      template: heads
    running:
      expression: workflow.status == "Running"
      template: heads
  templates:
    - name: main
      steps:
      - - name: step1
          hooks:
            running:
              expression: steps.step1.status == "Running"
              template: heads
          template: heads
    - name: heads
      container:
        image: alpine:3.6
        command: [sh, -c]
        args: ["echo \"{{workflows.status}}\""]
