apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: template-example-
spec:
  entrypoint: main
  templates:
    - name: main
      steps:
      - - name: add-four
          template: add-four
          arguments: {parameters: [{name: "a", value: "2"}]}
      - - name: print-number
          template: print-number
          when: "{{steps.add-four.outputs.result}} > 5"
          arguments: {parameters: [{name: "num", value: "{{steps.add-four.outputs.result}}"}]}
    - name: add-four
      inputs: {parameters: [{name: "a"}]}
      container:
        image: alpine:latest
        command: [sh, -c]
        args: ["echo $(( {{inputs.parameters.a}} + 4 ))"]
    - name: print-number
      inputs: {parameters: [{name: "num"}]}
      container:
        image: alpine:latest
        command: [sh, -c]
        args: ["echo {{inputs.parameters.num}}"]
