apiVersion: argoproj.io/v1alpha1
kind: EventBus
metadata:
  name: default
spec:
  jetstream:
    version: 2.8.1 
    # Optional, defaults to 3. If it is < 3, set it to 3, that is the minimal requirement.
    replicas: 3
