apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: workflow-template-add-four-
spec:
  entrypoint: whalesay
  templates:
  - name: whalesay
    steps:
    - - name: call-addfour-template
        templateRef:
          name: add-example-template
          template: addfour
        arguments:
          parameters:
          - name: a
            value: "3"
